### ISSUE TITLE
neva leave ur webhook out in da open

### ISSUE THREAD

**Issue by HausemasterIssue** [Sxmurai/aesthetirat#1]
we can use a webhook spammer lol, encode it with base64 or use pastebin or smthn

**Comment by Sxmurai** [comment]
its an invalid webhook spammer, and i was originally gonna make this encoded into something but meh im too lazy

**Comment by HausemasterIssue** [comment]
ah

**Comment by notperry1234567890** [comment]
> we can use a webhook spammer lol, encode it with base64 or use pastebin or smthn

Using Perryhook ofc 😼 .
