### ISSUE TITLE
fuck ass niggas still pastin my shit xD funny

### ISSUE THREAD

**Issue by monerowizard** [Sxmurai/aesthetirat#21]
be original or delete this shit

**Comment by monerowizard** [comment]
![изображение](https://user-images.githubusercontent.com/107992201/184127023-f031318a-7f59-4bd8-a448-fd120928b39d.png)
we still #1 in dis bih yall poor faggots wont never touch dis shi L o L

**Comment by master7720** [comment]
Who are you….

**Comment by Sxmurai** [comment]
My g this is an old ass project get tf outta here

**Comment by monerowizard** [comment]
My bad bro i was on percs yesterday i didnt see the date
