### ISSUE TITLE
keylogger

### ISSUE THREAD

**Issue by HausemasterIssue** [Sxmurai/aesthetirat#7]
make it start a keylogger on system startup

**Comment by master7720** [comment]
thats straight up going too far

**Comment by HausemasterIssue** [comment]
"browser data and accounts are straight up going too far. get rid of it please." - hausemasterissue 2021

**Comment by master7720** [comment]
> "browser data and accounts are straight up going too far. get rid of it please." - hausemasterissue 2021

yes xD

**Comment by notperry1234567890** [comment]
> make it start a keylogger on system startup

keylogger in a real rat is realistic but when ur using discord webhooks for a logger that's kinda more complicated but that is possible.

**Comment by Sxmurai** [comment]
Probably not, it doesn't make sense to add a keylogger tbh. I might come back to this later but for now, no.
